[build]
builder = "nixpacks"
buildCommand = "echo 'Building Stable Audio Tools microservice with Nixpacks'"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60  # Reduced since health check now always returns 200
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.development.variables]
ENVIRONMENT = "development"
LOG_LEVEL = "INFO"
# HuggingFace token for model access (REQUIRED) - Set in Railway environment variables
# Service authentication token
SERVICE_TOKEN = "dev-stable-audio-token-2024"
# Memory management
PYTHONMALLOC = "malloc"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
# Model cache settings
TRANSFORMERS_CACHE = "/tmp/transformers_cache"
TORCH_HOME = "/tmp/torch_cache"

[environments.production.variables]
ENVIRONMENT = "production"
LOG_LEVEL = "INFO"
# HuggingFace token for model access (REQUIRED) - Set in Railway environment variables
# Service authentication token
SERVICE_TOKEN = "prod-stable-audio-token-2024"
# Memory management for production
PYTHONMALLOC = "malloc"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
# Model cache settings
TRANSFORMERS_CACHE = "/tmp/transformers_cache"
TORCH_HOME = "/tmp/torch_cache"